title: <p align="center" Chaitanya Kavuri </p>
logo: /assets/img/New_Image.jpg
description: I'm working on Data Science, Big Data, Spark, Machine Learning & NLP related problems.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
